export const WishlistActionType = {
  TOGGLE_WISHLIST_HIDDEN: "TOGGLE_WISHLIST_HIDDEN",
  ADD_ITEM_WISHLIST: "ADD_ITEM_WISHLIST",
  REMOVE_ITEM_WISHLIST: "REMOVE_ITME_WISHLIST",
  CLEAR_ITEM_FROM_WISHLIST: "CLEAR_ITEM_FROM_WISLIST",
};
